name: Test

on:
  - push
  - workflow_dispatch

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt
      - run: pip download -r requirements.txt -r dev-requirements.txt
  pre-commit:
    needs: setup-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt
      - uses: pre-commit/action@v3.0.1
      - run: pip install -r dev-requirements.txt
