name: Test

on:
  pull_request:
    branches:
      - dev
jobs:
  qa:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
  test:
    needs: qa
    uses: ./.github/workflows/test.yml
