name: Test

on:
  pull_request:
    branches:
      - dev
jobs:
  qa:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1
  test:
    needs: qa
    uses: ./.github/workflows/test.yml
