name: Release Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.11"]
        include:
          - python-version: "3.12"
    uses: ./.github/workflows/test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
