name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: "string"
      os:
        required: false
        type: "string"

jobs:
  test:
    runs-on: ${{ inputs.os == '' && 'ubuntu-latest' || inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version == '' && '3.11' || inputs.python-version }}
