name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: "string"
        default: "3.11"
      os:
        required: false
        type: "string"
        default: "ubuntu-latest"

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: "pip"
          cache-dependency-path: |
            dev-requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: pytest | true # pytest gives an error code when it can't find tests so add
                           # true to ignore
