name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: "string"
        # default: ""
      os:
        required: false
        type: "string"
        # default: ""

jobs:
  test:
    runs-on: ${{ inputs.os || "ubuntu-latest" }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || "3.11"}}
          cache: "pip"
          cache-dependency-path: |
            dev-requirements.txt
      # do something like the below
      # - run: pip install -r dev-requirements.txt
      # - run: pytest

